name: Trigger auto deployment for container-app-vtza552z3uexi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-vtza552z3uexi-AutoDeployTrigger-bb90834d-0d63-49cd-8fa8-4d96443623bc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPVTZA552Z3UEXI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPVTZA552Z3UEXI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPVTZA552Z3UEXI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryvtza552z3uexi.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPVTZA552Z3UEXI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPVTZA552Z3UEXI_REGISTRY_PASSWORD }}
          containerAppName: container-app-vtza552z3uexi
          resourceGroup: expresssample90e0a8f3
          imageToBuild: containerregistryvtza552z3uexi.azurecr.io/container-app-vtza552z3uexi:${{ github.sha }}
          


